name: Generate ASCII Artwork

on:
  push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: List repo files
              run: ls -ltra

            - name: Executing shell script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh
    
            - name: Upload dragon text file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file

            - name: test job
              run: cat dragon.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: Download dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file
                            
            - name: deploy job
              run: cat dragon.txt
