name: Generate ASCII Artwork

on:
  push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: List repo files
              run: ls -ltra

            - name: Executing shell script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh
    
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: test job
              run: cat dragon.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: deploy job
              run: cat dragon.txt
